os: osx
osx_image: xcode11.3
env:
  global:
    - RUBYMOTION_LICENSE=1dcac45cc434293009f74b33037bdf7361a3a1ff # Official license key for open-source projects
    - TMP_DIR=./tmp  # For motion repo, so it doesn't attempt to use /tmp, to which it has no access
    - OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
before_install:
  - wget http://travisci.rubymotion.com/ -O RubyMotion-TravisCI.pkg
  - sudo installer -pkg RubyMotion-TravisCI.pkg -target /
  - cp -r /usr/lib/swift/*.dylib /Applications/Xcode.app/Contents/Frameworks/
  - touch /Applications/Xcode.app/Contents/Frameworks/.swift-5-staged
  - sudo mkdir -p ~/Library/RubyMotion/build
  - sudo chown -R travis ~/Library/RubyMotion
  - eval "sudo motion activate $RUBYMOTION_LICENSE"
  - sudo motion update
  - motion repo
script:
  - bundle exec rake spec device_name='iPad Pro (9.7-inch)'
